add essential logging strings to verify logging

diff --git a/.github/workflows/loggingTesting.yml b/.github/workflows/loggingTesting.yml
--- a/.github/workflows/loggingTesting.yml
+++ b/.github/workflows/loggingTesting.yml
@@ -8,7 +8,7 @@ jobs:
   test-logging:
     runs-on:
       group: databricks-protected-runner-group
-      labels: linux-ubuntu-latest
+      labels: [linux-ubuntu-latest, windows-server-latest]
 
     steps:
       - name: Checkout code
@@ -22,7 +22,6 @@ jobs:
 
       - name: Build JDBC driver
         run: mvn clean package -DskipTests
-
 
       - name: Set Environment Variables
         env:
@@ -39,13 +38,28 @@ jobs:
           javac -cp target/databricks-jdbc-0.9.9-oss.jar src/test/java/com/databricks/client/jdbc/LoggingTest.java
           java --add-opens=java.base/java.nio=ALL-UNNAMED -cp target/databricks-jdbc-0.9.9-oss.jar:target/classes com.databricks.client.jdbc.LoggingTest
 
-
-      - name: Print logs from /tmp/logstest/databricks_jdbc.log.0
+      - name: Verify log file contents
         run: |
-          echo "Printing logs"
+          echo "Verifying log file contents..."
           if [ -f "/tmp/logstest/databricks_jdbc.log.0" ]; then
-            echo "Log file contents:"
-            cat /tmp/logstest/databricks_jdbc.log.0
+            echo "Log file found. Checking contents..."
+          
+            REQUIRED_STRINGS=("Executed sql [SELECT current_version().dbsql_version] with status [SUCCEEDED]"
+                              "Executing HTTP request"
+                              "Result retrieved successfully"
+                              "Parsing data for chunk index [0]"
+                              "Data parsed for chunk index [0]"
+                              "Closing global async HTTP client"
+                              "Global async HTTP client has been shut down")
+
+            for STRING in "${REQUIRED_STRINGS[@]}"; do
+              if ! grep -q "$STRING" /tmp/logstest/databricks_jdbc.log.0; then
+                echo "ERROR: Required log string not found: $STRING"
+                exit 1
+              fi
+            done
+
+            echo "All required log strings were found."
           else
             echo "Log file /tmp/logstest/databricks_jdbc.log.0 does not exist. Failing the build."
             exit 1
